class RepositorioEmprestimo:

    def buscar_equipamento(self, equip_id):
        ...

    def salvar_emprestimo(self, emprestimo):
        ...

    def marcar_indisponivel(self, equip_id):
        ...

    def buscar_emprestimo(self, emprestimo_id):
        ...

    def marcar_devolvido(self, emprestimo_id):
        ...

    def marcar_disponivel(self, equipamento_id):
        ...

    def listar_emprestimos(self):
        ...
